# Generated by Django 2.0.7 on 2020-03-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Load',
        ),
    ]
